# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
# Variable Group 'Test' was defined in the Variables tab
# Variable Group 'FE variable' was defined in the Variables tab
trigger:
  branches:
    include:
      - releases/*
      - dev
      - main
  batch: true
name: $(SourceBranchName)_$(Date:ddMMyyyy)$(Rev:.r)

jobs:
  - job: Job_1
    displayName: Agent job 1
    pool:
      name: Builder
    steps:
      - checkout: self
      - task: CmdLine@2
        displayName: Prebuild
        inputs:
          script: |
            docker build -t supermedicalchain/nginx:pre-release --target=release .
      - task: CmdLine@2
        displayName: Build
        inputs:
          script: |
            docker login -u $(DOCKER_USERNAME) -p $(DOCKER_PASSWORD)
            docker tag supermedicalchain/nginx:pre-release supermedicalchain/nginx:${TAG}
            docker push supermedicalchain/nginx:${TAG}
      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact: deploy'
        inputs:
          PathtoPublish: deploy
          ArtifactName: deploy
...